# Generated by Django 4.1 on 2023-02-10 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wishesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.TextField(max_length=100)),
                ('cat_img', models.FileField(blank=True, upload_to='wishesImg/')),
                ('cat_des', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='wishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wish', models.TextField()),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wishes.wishescategory')),
            ],
        ),
    ]
