# Generated by Django 4.1 on 2023-02-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishes',
            name='subcategory',
            field=models.TextField(default='normal', max_length=50),
            preserve_default=False,
        ),
    ]
