# Generated by Django 4.1 on 2023-02-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0002_wishes_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishes',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
